# Form implementation generated from reading ui file 'app/ui/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 340)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #f0f0f0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3c3c3c;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #444;\n"
"    border: 1px solid #666;\n"
"    padding: 5px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logged_in_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.logged_in_label.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.logged_in_label.setObjectName("logged_in_label")
        self.UsernameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(200, 30, 161, 51))
        self.UsernameLabel.setObjectName("UsernameLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logged_in_label.setText(_translate("MainWindow", "You are logged in as: "))
        self.UsernameLabel.setText(_translate("MainWindow", "<h1> Username </h1>"))
