# Form implementation generated from reading ui file 'app/ui/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 340)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #f0f0f0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3c3c3c;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #444;\n"
"    border: 1px solid #666;\n"
"    padding: 5px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: rgb(98, 98, 98);\n"
"    border-radius: 15px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loggedInLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.loggedInLabel.setGeometry(QtCore.QRect(250, 20, 131, 21))
        self.loggedInLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loggedInLabel.setObjectName("loggedInLabel")
        self.UsernameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(240, 40, 151, 41))
        self.UsernameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.logoutButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(30, 10, 101, 31))
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 89, 381, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VaultTable = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.VaultTable.setAlternatingRowColors(True)
        self.VaultTable.setColumnCount(4)
        self.VaultTable.setObjectName("VaultTable")
        self.VaultTable.setRowCount(0)
        self.verticalLayout.addWidget(self.VaultTable)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 201, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.removeButton = QtWidgets.QToolButton(parent=self.horizontalLayoutWidget)
        self.removeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app/ui\\icons/minus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.removeButton.setIcon(icon)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.editButton = QtWidgets.QToolButton(parent=self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("app/ui\\icons/pen-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.editButton.setIcon(icon1)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.addButton = QtWidgets.QToolButton(parent=self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("app/ui\\icons/plus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addButton.setIcon(icon2)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loggedInLabel.setText(_translate("MainWindow", "Welcome back!"))
        self.UsernameLabel.setText(_translate("MainWindow", "<h1> Username </h1>"))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.editButton.setText(_translate("MainWindow", "..."))
        self.addButton.setText(_translate("MainWindow", "..."))
