# Form implementation generated from reading ui file 'app/ui/dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(557, 241)
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #f0f0f0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3c3c3c;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"    color: #f0f0f0;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #444;\n"
"    border: 1px solid #666;\n"
"    padding: 5px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"\n"
"#infoLabel {\n"
"    background-color:rgb(255, 3, 3);\n"
"    padding: 5px;\n"
"     border-radius: 25px;\n"
"}\n"
"\n"
"QToolButton. QDialogButtonBox {\n"
"    background-color: #3c3c3c;\n"
"    border-radius: 15px;\n"
"}")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 140, 211, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.URLVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.URLVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.URLVerticalLayout.setObjectName("URLVerticalLayout")
        self.URLLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.URLLabel.setObjectName("URLLabel")
        self.URLVerticalLayout.addWidget(self.URLLabel)
        self.URLInput = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_3)
        self.URLInput.setObjectName("URLInput")
        self.URLVerticalLayout.addWidget(self.URLInput)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 251, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.passwordVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.passwordVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.passwordVerticalLayout.setObjectName("passwordVerticalLayout")
        self.passwordLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.passwordVerticalLayout.addWidget(self.passwordLabel)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.passwordInput.setObjectName("passwordInput")
        self.passwordVerticalLayout.addWidget(self.passwordInput)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(276, 40, 271, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.usernameVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.usernameVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.usernameVerticalLayout.setObjectName("usernameVerticalLayout")
        self.usernameLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.usernameLabel.setObjectName("usernameLabel")
        self.usernameVerticalLayout.addWidget(self.usernameLabel)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget_2)
        self.usernameInput.setObjectName("usernameInput")
        self.usernameVerticalLayout.addWidget(self.usernameInput)
        self.optionLabel = QtWidgets.QLabel(parent=Dialog)
        self.optionLabel.setGeometry(QtCore.QRect(210, 10, 151, 16))
        self.optionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.optionLabel.setObjectName("optionLabel")
        self.saveButton = QtWidgets.QToolButton(parent=Dialog)
        self.saveButton.setGeometry(QtCore.QRect(20, 10, 30, 21))
        self.saveButton.setStyleSheet("QToolButton {\n"
"    \n"
"    background-color: rgb(139, 139, 139);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app/ui\\icons/floppy-disk-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.saveButton.setIcon(icon)
        self.saveButton.setObjectName("saveButton")
        self.URLListWidget = QtWidgets.QListWidget(parent=Dialog)
        self.URLListWidget.setGeometry(QtCore.QRect(280, 140, 251, 81))
        self.URLListWidget.setObjectName("URLListWidget")
        self.addURLButton = QtWidgets.QToolButton(parent=Dialog)
        self.addURLButton.setGeometry(QtCore.QRect(240, 140, 31, 31))
        self.addURLButton.setStyleSheet("QToolButton {\n"
"    \n"
"    background-color: rgb(139, 139, 139);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("app/ui\\icons/plus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addURLButton.setIcon(icon1)
        self.addURLButton.setObjectName("addURLButton")
        self.removeURLButton = QtWidgets.QToolButton(parent=Dialog)
        self.removeURLButton.setGeometry(QtCore.QRect(240, 190, 31, 31))
        self.removeURLButton.setStyleSheet("QToolButton {\n"
"    \n"
"    background-color: rgb(139, 139, 139);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("app/ui\\icons/minus-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.removeURLButton.setIcon(icon2)
        self.removeURLButton.setObjectName("removeURLButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.URLLabel.setText(_translate("Dialog", "URL Label Placeholder"))
        self.URLInput.setText(_translate("Dialog", "URL_input_placeholder"))
        self.passwordLabel.setText(_translate("Dialog", "Password Label Placeholder"))
        self.passwordInput.setText(_translate("Dialog", "password_input_placeholder"))
        self.usernameLabel.setText(_translate("Dialog", "Username Label Placeholder"))
        self.usernameInput.setText(_translate("Dialog", "username_input_placeholder"))
        self.optionLabel.setText(_translate("Dialog", "Placeholder"))
        self.saveButton.setText(_translate("Dialog", "..."))
        self.addURLButton.setText(_translate("Dialog", "..."))
        self.removeURLButton.setText(_translate("Dialog", "..."))
