# Form implementation generated from reading ui file 'app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 340)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #f0f0f0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #3c3c3c;\n"
"    border: 1px solid #555;\n"
"    padding: 5px;\n"
"    color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #444;\n"
"    border: 1px solid #666;\n"
"    padding: 5px;\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"\n"
"#infoLabel {\n"
"    background-color:rgb(255, 3, 3);\n"
"    padding: 5px;\n"
"     border-radius: 25px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 50, 211, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.usernameLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout.addWidget(self.usernameInput)
        self.passwordLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(160, 250, 71, 31))
        self.loginButton.setObjectName("loginButton")
        self.infoLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(150, 10, 91, 31))
        self.infoLabel.setObjectName("infoLabel")
        self.switchToRegisterButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.switchToRegisterButton.setGeometry(QtCore.QRect(310, 270, 101, 41))
        self.switchToRegisterButton.setObjectName("switchToRegisterButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameLabel.setText(_translate("MainWindow", "Username:"))
        self.passwordLabel.setText(_translate("MainWindow", "Password:"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.infoLabel.setText(_translate("MainWindow", "Placeholder"))
        self.switchToRegisterButton.setText(_translate("MainWindow", "Go to Register"))
